#ifndef PHYSICS_DEFAULTS_H
#define PHYSICS_DEFAULTS_H

#define PHYSICS_DEFAULT_TIME_STEP (1.0f / 60.0f)
#define PHYSICS_DEFAULT_SUBSTEPS 3
#define PHYSICS_DEFAULT_ITERATIONS 5
#define PHYSICS_DEFAULT_DAMPING 0.99f
#define PHYSICS_DEFAULT_BROADPHASE_CELL_SIZE 10.0f
#define PHYSICS_DEFAULT_MAX_POSITION_ITERATION_BIAS 3
#define PHYSICS_DEFAULT_GRAVITY_X 0.0f
#define PHYSICS_DEFAULT_GRAVITY_Y 9.8f

#define PHYSICS_DEFAULT_EXPERIMENTAL_CCD 0
#define PHYSICS_DEFAULT_EXPERIMENTAL_SLEEP 0
#define PHYSICS_DEFAULT_EXPERIMENTAL_THREADING 0
#define PHYSICS_DEFAULT_EXPERIMENTAL_WORKERS 1

#endif
