#ifndef PHYSICS_TUNING_H
#define PHYSICS_TUNING_H

/* Sleep tuning */
#define PHYSICS_TUNE_SLEEP_LINEAR 0.06f
#define PHYSICS_TUNE_SLEEP_ANGULAR 0.10f
#define PHYSICS_TUNE_SLEEP_CONTACT_LINEAR 0.25f
#define PHYSICS_TUNE_SLEEP_CONTACT_ANGULAR 0.25f
#define PHYSICS_TUNE_SLEEP_TIME 0.45f

/* Wakeup tuning */
#define PHYSICS_TUNE_WAKE_IMPULSE_THRESHOLD 0.2f

/* Contact manifold tuning */
#define PHYSICS_TUNE_POLYGON_BAND_EPS 0.02f
#define PHYSICS_TUNE_CONTACT_CACHE_NORMAL_LIMIT 24.0f
#define PHYSICS_TUNE_CONTACT_CACHE_TANGENT_LIMIT 16.0f

/* Restitution and bounce tuning */
#define PHYSICS_TUNE_BOUNCE_THRESHOLD_CIRCLE_POLYGON 2.2f
#define PHYSICS_TUNE_BOUNCE_THRESHOLD_CIRCLE 1.2f
#define PHYSICS_TUNE_BOUNCE_THRESHOLD_POLYGON 0.8f
#define PHYSICS_TUNE_RESTITUTION_CIRCLE_POLYGON_SCALE 0.88f
#define PHYSICS_TUNE_TARGET_SEPARATION_CIRCLE_POLYGON_SCALE 0.92f
#define PHYSICS_TUNE_EXTRA_IMPULSE_SCALE_CIRCLE_POLYGON 0.8f
#define PHYSICS_TUNE_EXTRA_IMPULSE_SCALE_DEFAULT 1.2f

/* Friction tuning */
#define PHYSICS_TUNE_STATIC_FRICTION_SCALE_CIRCLE_POLYGON 0.08f
#define PHYSICS_TUNE_STATIC_FRICTION_SCALE_CIRCLE 0.35f
#define PHYSICS_TUNE_STATIC_FRICTION_SCALE_POLYGON 1.25f
#define PHYSICS_TUNE_DYNAMIC_FRICTION_SCALE_CIRCLE_POLYGON 0.05f
#define PHYSICS_TUNE_DYNAMIC_FRICTION_SCALE_CIRCLE 0.25f
#define PHYSICS_TUNE_DYNAMIC_FRICTION_SCALE_POLYGON 0.85f
#define PHYSICS_TUNE_ROLLING_RESISTANCE_SCALE 0.03f

/* Positional correction tuning */
#define PHYSICS_TUNE_POS_SLOP_DEFAULT 0.005f
#define PHYSICS_TUNE_POS_PERCENT_DEFAULT 0.35f
#define PHYSICS_TUNE_POS_MAX_CORRECTION_DEFAULT 0.6f
#define PHYSICS_TUNE_POS_SLOP_CIRCLE_POLYGON 0.001f
#define PHYSICS_TUNE_POS_PERCENT_CIRCLE_POLYGON 0.88f
#define PHYSICS_TUNE_POS_MAX_CORRECTION_CIRCLE_POLYGON 2.8f
#define PHYSICS_TUNE_POS_WEIGHT_BIAS_CIRCLE 2.4f
#define PHYSICS_TUNE_POS_WEIGHT_BIAS_POLYGON 0.12f

/* Constraint tuning */
#define PHYSICS_TUNE_CONSTRAINT_MIN_STIFFNESS 0.08f
#define PHYSICS_TUNE_CONSTRAINT_SPRING_MIN_STIFFNESS 0.20f
#define PHYSICS_TUNE_CONSTRAINT_SPRING_POS_CORRECTION_SCALE 0.0005f
#define PHYSICS_TUNE_CONSTRAINT_SPRING_POS_CORRECTION_MAX 0.03f
#define PHYSICS_TUNE_CONSTRAINT_IMPULSE_LIMIT 18.0f

#endif
